from instagram.apps.authentication.serializers.auth import SignUpSerializer as SignUpSerializer
from instagram.apps.authentication.serializers.auth import AccountVerificationSerializer as AccountVerificationSerializer
from instagram.apps.authentication.serializers.auth import LoginSerializer as LoginSerializer
from instagram.apps.authentication.serializers.password import PasswordResetSerializer as PasswordResetSerializer