# Generated by Django 4.1.4 on 2022-12-27 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('full_name', models.CharField(max_length=150, verbose_name='full name')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='users/profile', verbose_name='picture picture')),
                ('biography', models.TextField(verbose_name='biography')),
                ('link', models.URLField(blank=True, null=True, verbose_name='website')),
                ('is_public', models.BooleanField(default=True, verbose_name='is public')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
